name: Terraform Plan

on:
  push:
    branches:
      - master  # Run Terraform Plan on push to main

jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Save data
        run: echo "Hello World!" > data.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-data
          path: data.txt

  job2:
    needs: job1
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: my-data
      - name: Read data
        run: cat data.txt

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Terraform & Terragrunt
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          wget -q https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
          unzip terraform_1.6.0_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          wget -q https://github.com/gruntwork-io/terragrunt/releases/latest/download/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
          terragrunt --version  # Verify installation

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.x

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::794038223971:role/githubrole2
          aws-region: us-east-1  # Change based on your AWS region

      - name: Terraform Init
        run: terragrunt run-all init --terragrunt-working-dir envs/dev

    #   - name: Terraform Format
    #     run: terraform run-all fmt --terragrunt-working-dir envs/dev

    #   - name: Terraform Validate
    #     run: terraform run-all validate --terragrunt-working-dir envs/dev

      - name: Terraform Plan
        run: terragrunt run-all plan -out=tfplan --terragrunt-working-dir envs/dev
