name: Print GitHub Reference

on:
  push:
    branches:
      - master  # Runs on pushes to the master branch
    tags:
      - '*'  # Runs on any tag push

jobs:
  versioned-tag-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub Reference
        run: echo "Triggered by: ${{ github.ref }}"
